### ISSUE TITLE
Add styling for collection/object content

### ISSUE THREAD

**Issue by helrond** [RockefellerArchiveCenter/dimes#130]
## Is your feature request related to a problem? Please describe.
Additional styling is needed for the collection and object content.

## Describe the solution you'd like
Add styles to:
- Show lines linking child components to parents
- wrap objects in border with parent

**Comment by HaSistrunk** [comment]
Can we also throw in left-aligning the title with the other content as part of this issue?  

![image](https://user-images.githubusercontent.com/15254041/94838455-9b20a700-03e3-11eb-9654-87f948abdcd7.png)
