### ISSUE TITLE
Error fetching list item data

### ISSUE THREAD

**Issue by HaSistrunk** [RockefellerArchiveCenter/dimes#136]
## Describe the bug
The My List page is throwing an error in the resolveList function related to fetching ancestor data.

## To reproduce
Add object to My List and click on My List link.

## Error message or screenshots
![image](https://user-images.githubusercontent.com/15254041/94939774-953ccb80-04a0-11eb-9e9c-9cbd27adfe77.png)

**Comment by helrond** [comment]
There's code in `base` right now which should address this: 
https://github.com/RockefellerArchiveCenter/dimes/commit/fc351001e383a2a0ce02d19d9848506366fec48c

**Comment by HaSistrunk** [comment]
Oh! Right, thank you. Closing this.
