### ISSUE TITLE
Enable "inside this collection" modal on agent page

### ISSUE THREAD

**Issue by HaSistrunk** [RockefellerArchiveCenter/dimes#186]
## Is your feature request related to a problem? Please describe.
The # matches button in the collection tiles only open the Inside the Collection modal in the Search Results page, but not on the agent page in related collections

## Describe the solution you'd like
The # matches buttons should operate the same on both pages

## Additional context
This isn't a major priority if we want to wait until search usability testing to see how these buttons hold up in testing.

**Comment by helrond** [comment]
I am noticing that the mockups *don't* have the hit counts on them. I think we can wait a bit on this one, but one other course of action is to hide those badges on agent pages. I'm not sure they're as meaningful in this context.
