### ISSUE TITLE
Create Tree components

### ISSUE THREAD

**Issue by HaSistrunk** [RockefellerArchiveCenter/dimes#21]
## Describe the solution you'd like
A set of tree view components to enable browsing of nested collections/objects.

## Additional context
See [Instructure TreeBrowser](https://instructure.design/#TreeBrowser). This component should be created with consideration/in conversation with the Accordion component (issue #5 ) in thinking about the best strategy for handling nested collection/object navigation.

**Comment by helrond** [comment]
closing in favor of #133
