### ISSUE TITLE
Improve awareness of and access to digital materials

### ISSUE THREAD

**Issue by HaSistrunk** [RockefellerArchiveCenter/dimes#217]
## Is your feature request related to a problem? Please describe.
Better surface the fact that there is digital content available to view online and facilitate users' ability to find that content.

## Describe the solution you'd like
Add "digital content" or "digital materials" to the dropdown option in the search select menu. Using "digital content" as a descriptor mirrors the language used on the homepage: "Search Our Collections. Discover People and Organizations. Access Digital Content," but our current facet read "show me digital materials only." I'm not sure which is better.

## Describe alternatives you've considered
1. Add a checkbox associated with the search form that specifies something like "show me digital materials only," as a way to include that facet at the start of the search process.
2. Do nothing and keep testing this with users.

**Comment by helrond** [comment]
Been looking at this a bit, and there are a couple of potential pitfalls here that we might want to consider:
- Adding "Digital Content" to the drop-down list complicates handling of that value in translation to URL parameters and back
- We'd also need to find a way to keep that value and the checkbox in the facet in sync with each other
- Perhaps most significantly, other options in the dropdown are mutually exclusive, so if a user didn't notice the checkbox in the facet they'd never be able to search for collections + digital content. In terms of what this produces in search results there may not be a huge difference but in terms of presenting an understandable mental model to users it falls pretty far short.

To my mind, the checkbox option is a good one (and if we go that route I'd argue for pulling the checkbox out of the facet) but I'm also not sure we've observed this as a problem yet (or if we have, I don't know that we've fully understood the implications of the problem yet). So, for the moment, let's hold off on doing anything and keep an eye on this in further tests.

**Comment by HaSistrunk** [comment]
Following up: the latest round of usability testing pointed to this being a problem, in that users looked to the "Format" facets to find digital content, and made various assumptions about all of the content in DIMES being available to view online, or weren't sure what that facet meant. I think this points to the usefulness of pulling the checkbox out of the facet and including it as part of the search form, even if it may not bring total clarity.

If we go this route, the language that is used to convey what this facet is is important. Ideas (or some combo of these):
- Filter for materials that I can access online
- Only search digital content
- Digital selections only
- Available online

**Comment by helrond** [comment]
Great, sounds like a plan. 

Let's wait for a design solution before trying to implement this.

**Comment by HaSistrunk** [comment]
We now have a preliminary design solution for this issue: [https://projects.invisionapp.com/share/8R10HL79AF52#/screens](https://projects.invisionapp.com/share/8R10HL79AF52#/screens). Note that this consists of:
1. Pulling the digital materials filter out of the filters modal
2. Implementing a checkbox to modify search results to only include digital materials both on the homepage and the search results page
3. Suggests changing the select dropdown to replace "Everything" with "All types"
