### ISSUE TITLE
Add ability to download from digital object viewer

### ISSUE THREAD

**Issue by HaSistrunk** [RockefellerArchiveCenter/dimes#252]
## Is your feature request related to a problem? Please describe.
It would be a nice feature to be able to download directly from the digital object viewer, rather than go back to the item details to accomplish this.

## Describe the solution you'd like
Investigate Mirador to see if this is a possibility.

## Describe alternatives you've considered
- Do nothing

**Comment by helrond** [comment]
This is definitely possible with [this plugin](https://github.com/ProjectMirador/mirador-dl-plugin), but we need to decide *what* should be downloaded from the viewer: a high-res representation of a single page, or a low-res version of everything (i.e. a TIFF or a PDF). There are some cost considerations involved as well.

Any implementation should be done in tandem with #248

**Comment by helrond** [comment]
Added this to the post-release design list. In addition to the above considerations, we'll also have to think about 1) where this button goes and 2) responsive styles.

**Comment by helrond** [comment]
We now have styles for this:
- [desktop](https://invis.io/Z810HL98YU7Q)
- [mobile](https://invis.io/7H10RCWHDAQY)
