### ISSUE TITLE
Display suggested search terms

### ISSUE THREAD

**Issue by helrond** [RockefellerArchiveCenter/dimes#272]
## Is your feature request related to a problem? Please describe.
Misspellings of names or other terms can cause users to miss hits.

## Describe the solution you'd like
Display suggested search terms. Would need to decide if these suggestions would always be display, or only sometimes. If it's the latter, we'd then need to come up with some criteria for when they are displayed.

## Additional context
We should probably wait for a design solution before trying to implement this.

**Comment by HaSistrunk** [comment]
We now have a design solution that displays suggested terms when there are no results. We can move ahead and implement that: [https://projects.invisionapp.com/share/G510HL8V8ARD#/screens](https://projects.invisionapp.com/share/G510HL8V8ARD#/screens)
