### ISSUE TITLE
Nav header doesn't appear in digital object viewer

### ISSUE THREAD

**Issue by HaSistrunk** [RockefellerArchiveCenter/dimes#279]
## Describe the bug
Nav header isn't showing up in the digital object viewer, although it is in the DOM, so this appears to be a layout issue. I'm wondering if PR #218 's solution to use `fixed` and add a top margin to #main effected this based on what is designated as #main on this page?

## To reproduce
Open the digital object viewer. Example: /objects/UhixZnaWBmeXGNkZ74hYpE/view. Notice that you can inspect the page and see the header in the code, as well as tab through the links, but it is not visible.

**Comment by helrond** [comment]
I don't think the nav has *ever* been visible on the digital object viewer page. I think this is a function of the default Mirador styles.
