### ISSUE TITLE
Matches do not appear in collection context when faceting for moving image format

### ISSUE THREAD

**Issue by HaSistrunk** [RockefellerArchiveCenter/dimes#316]
## Describe the bug
The facet for moving image format appears to be functioning as expected. However, when the user clicks into a collection after faceting for moving image content, the matches badges do not appear.

## To reproduce
1. Search for anything with moving image formats
2. Select the moving image checkbox to facet for that content
3. Click into any collection
4. See that the matches badges do not appear

Other formats seem to be working/displaying matches as expected.

**Comment by helrond** [comment]
This is an argo problem. Issue filed at RockefellerArchiveCenter/argo#139
