### ISSUE TITLE
Use styling to create non-semantic newlines in footer

### ISSUE THREAD

**Issue by HaSistrunk** [RockefellerArchiveCenter/dimes#33]
## Is your feature request related to a problem? Please describe.
Screen reader pauses at a new line, so when reading the heading "Rockefeller Archive Center" in the footer, it would pause between the first and second words because there is a `<br>` element there. The current `aria-label` is one way around that, but not ideal since this solution uses html for styling.

## Describe the solution you'd like
Replace `<br>` elements with styling to achieve a new line in the `<h2>` of the footer. 

## Describe alternatives you've considered
If we decide to make this change, we can remove the aria-label. If we decide not to make the change, we can leave as-is.

## Additional context
[https://css-tricks.com/injecting-line-break/](https://css-tricks.com/injecting-line-break/)

**Comment by Tyl13** [comment]
This doesn't actually seem to fix the problem on NVDA from a quick test by me. I enabled the screen viewer for NVDA to show what is was reading out completely.

This is your current implementation:
<img width="960" alt="Current Footer solution (seems to be not working)" src="https://user-images.githubusercontent.com/48526589/229153242-566f6ea7-a7e3-4d73-bd56-ba4bf8813ebe.png">
It shows that it is not treating Rockefeller Archive Center as a single element to be said.

This was a solution that I found, that seems to work:
<img width="953" alt="Working screen reader" src="https://user-images.githubusercontent.com/48526589/229153700-ff84b2e2-8d28-4e51-92aa-340872b11903.png">
I don't necessarily like this solution a lot. The idea of using a <br> just as presentation isn't great to me but it does seem as an alright thing to do. This is based on https://w3c.github.io/html-aria/#el-br , https://www.w3.org/TR/wai-aria-1.2/#presentation and https://webaim.org/techniques/aria/ .

Another option is to use the Aria-Label but that still needs to have an actual line break within the header anyways.

**Comment by HaSistrunk** [comment]
Thanks for troubleshooting this! I'm finding that none of these solutions (or the current implementation of the `<span class="line-break">` work seamlessly on VoiceOver. Apparently it's just very verbose and splits the heading into two items and reads them out separately in all of the above solutions. 

In my mind, this is a slight usability annoyance for VoiceOver users, but not a major issue, and your `<br role="presentation">` suggestion will at least improve things for NVDA users. The only other possibility might be to have two headings, one with `aria-hidden` that includes the break, and one as SR-only. That feels very clunky, though.

**Comment by Tyl13** [comment]
That's odd. What happens with the aria-`label solution`? Does it just read both the label and the header text, or does it skip the label entirely?

Yeah, that solution would probably work. You could also probably put two different elements, like two `<p>` elements within the header and just hide the one. That way accessibility testers like WAVE won't get angry about a hidden header. Though WAVE doesn't like that it seems either, and is instead okay with the hidden `<h1>`. That seems odd to me. This seems to work for NVDA at least. I worry that if VoiceOver is ignoring `aria-label` then it will ignore the `aria-hidden` too.

<img width="960" alt="Hidden aria, but correct text within one header" src="https://user-images.githubusercontent.com/48526589/229184702-1abae673-d211-43ee-ace1-d89d6d83545b.png">

**Comment by HaSistrunk** [comment]
Apologies for the slow response on this! Using aria-label and aria-hidden do work as expected with VoiceOver, so how's this approach?

<img width="884" alt="image" src="https://github.com/RockefellerArchiveCenter/dimes/assets/15254041/b85ab9e0-f831-4806-8dd1-501aa970e347">

**Comment by Tyl13** [comment]
It's fine. Yeah, that also seems to work as expected with NVDA.
