### ISSUE TITLE
Pagination in search results indicate more pages/results than are displayed

### ISSUE THREAD

**Issue by HaSistrunk** [RockefellerArchiveCenter/dimes#352]
## Describe the bug
In the Search Results page, the number of results and pages of results are much higher than the actual results displayed.

## To reproduce
1. Search for something like "Nelson"
2. See pagination section of search results page.
3. Click through the search results pages
4. Notice that only the first few have results displayed, and the rest are blank.
5. Notice that the number of results returned are much higher than the actual number of results displayed

## Expected behavior
Number of results indicated in pagination should match the number of results displayed.

## Error message or screenshots
![image](https://user-images.githubusercontent.com/15254041/107557009-128ef000-6ba7-11eb-8a71-5191a4d95d97.png)

## Additional context
This may be an Argo issue.

**Comment by helrond** [comment]
@HaSistrunk I have implemented a potential fix for this in development argo - would you be able to test against that API and see if that resolves the issue?

**Comment by HaSistrunk** [comment]
Yes, I can confirm after testing against Argo development that the results/pagination are working as expected there and the issue is resolved.

**Comment by helrond** [comment]
Awesome, will merge that to `base`!
