### ISSUE TITLE
Digital object pages do not preserve query params

### ISSUE THREAD

**Issue by HaSistrunk** [RockefellerArchiveCenter/dimes#426]
## Is your feature request related to a problem? Please describe.
When a user searches and finds a digital item, opens to view the item, and then returns to its object page using the "Back to item details" button, the url query parameters are no longer part of the URL so they lose their search matches. We haven't had this articulated to us as an issue, but with the minimap feature this might be more obvious to folks since the minimap will be blank once they return to the object page. 

## Describe the solution you'd like
Is it possible to maintain the search query terms in the url when viewing a digital object? The user can achieve this by just using the browser back button, but I would expect the "back to item details" button to function the same way.

**Comment by helrond** [comment]
@HaSistrunk I am unable to reproduce this, and there is [code](https://github.com/RockefellerArchiveCenter/dimes/blob/base/src/components/PageDigitalObject/index.js#L90-L93) which preserves the query params. Can you give me more specifics about the digital object where this occurred and the user flow preceding it? I am wondering if it's specific to a particular object.

**Comment by HaSistrunk** [comment]
> @HaSistrunk I am unable to reproduce this, and there is [code](https://github.com/RockefellerArchiveCenter/dimes/blob/base/src/components/PageDigitalObject/index.js#L90-L93) which preserves the query params. Can you give me more specifics about the digital object where this occurred and the user flow preceding it? I am wondering if it's specific to a particular object.

Ah, I'm now seeing it only happens if you select the "View item" button for an object that you haven't already selected.

For example:
1. Go to the url: https://dimes.rockarch.org/collections/NhywnnvXZufAaZNXLeA5kQ?category=&limit=40&query=agriculture
2. Click "View item" for any digital item
3. Click the "back to item details" button
4. Note the url

Compared to:
1. Go to the same url: https://dimes.rockarch.org/collections/NhywnnvXZufAaZNXLeA5kQ?category=&limit=40&query=agriculture
2. Select an object that is available to view online
3. Click the "View item" button for that selected item
4. Click the "back to item details" button
5. Note the url

**Comment by helrond** [comment]
Thanks @HaSistrunk - I would never have caught this. I've updated the logic in 2416b0479e3f8904440d35c7297fc11340378971 so that params are always used if they're present.
