### ISSUE TITLE
Sibling objects above selected object not loading as expected

### ISSUE THREAD

**Issue by HaSistrunk** [RockefellerArchiveCenter/dimes#427]
## Describe the bug
With the addition of new loading strategy with the minimap, sibling objects above a selected object are not loading as expected when the user scrolls up. The first set will load when the user scrolls up, but then the next set do not until the user scrolls back down and then up again.

There does not appear to be any loading issues with the objects _below_ the selected object, only above.

## To reproduce
1. Go to a specific object url, either directly with the url or by clicking on a minimap square (eg. objects/W9jBzNTBe4TuGzT8FTyoZQ)
2. Scroll up to see object above the selected object load. See that the next set of objects appears. 
3. Keep scrolling up and see that the next set of objects do not load.
4. Scroll back down to view the loaded objects below until the loading objects' skeletons are not visible on the screen, and then scroll back up and the next set of objects _does_ load this time.

## Expected behavior
As the user scrolls up, the next set of objects loads.

## Error message or screenshots
I don't see any specific errors, although there are warnings in the build related to React Hook useEffect having missing dependencies. I'm not sure if that's related, though.

## Impact on your work
Hinders ability to view sibling objects.

**Comment by helrond** [comment]
Should be fixed by 33d0c8e
