### ISSUE TITLE
Collection content not always loading as expected with browser back button

### ISSUE THREAD

**Issue by HaSistrunk** [RockefellerArchiveCenter/dimes#433]
## Describe the bug
Collection content not loading when a user navigates back (with the browser “back” button) in specific circumstances (see steps to reproduce).

## To reproduce
1. Go to any dimes object or collection URL Example: [https://dimes.rockarch.org/objects/ZB6KygNj8LPCnm83ftwRiF](https://dimes.rockarch.org/objects/ZB6KygNj8LPCnm83ftwRiF )
2. Select any other object or collection in the Collection Content 
3. Click the browser “back” button 
4. Observe Collection Content 

## Expected behavior
When the user hits the back button, the full Collection Content would appear around the selected collection/object, just as it did when the user went directly to that URL in the first place.

## Error message or screenshots
No errors observed.

## Impact on your work
Not hard to recover from, but definitely unexpected.

## Additional context
This happened to a user during a usability test.

**Comment by helrond** [comment]
fixed by 9329efc49a58572c6ccbb8577c6d05f82ff8b0f6
