### ISSUE TITLE
Correctly apply focus styles for selected objects

### ISSUE THREAD

**Issue by HaSistrunk** [RockefellerArchiveCenter/dimes#434]
## Describe the bug
In `minimap-square` branch, focus styles that highlight which object is currently selected are not being applied when a user opens a specific object URL (either by click on minimap square or opening with a URL in the browser). 

## To reproduce
1. Open http://localhost:3000/objects/ZB6KygNj8LPCnm83ftwRiF/ (from minimap-squares branch) 
2. Open dimes.rockarch.org/objects/ZB6KygNj8LPCnm83ftwRiF/  
3. Compare focus styles for object in Collection Contents 

## Expected behavior
When an object page is open, that object should have focus styles applied to the object in the Collection Content.

## Error message or screenshots
None

## Impact on your work
As we observed in previous DIMES usability testing, having a focus style helps the user orient which object is currently selected and find it again if they scroll away from it.

**Comment by helrond** [comment]
fixed by 647cf5d98576047305b89deb2de9cc22235353c0
