### ISSUE TITLE
Make minimap links only point to object hits

### ISSUE THREAD

**Issue by HaSistrunk** [RockefellerArchiveCenter/dimes#435]
## Is your feature request related to a problem? Please describe.
With minimap feature, usability testing showed that users did not expect/were confused when map links pointed to a collection hit.

## Describe the solution you'd like
Add logic to make sure that minimap links always point to an object hit, rather than a collection hit. Consider how to deal with cases where there are no object hits.

**Comment by helrond** [comment]
fixed in f54e977285c8833f32e19fe839e4ec15e978b3fb
