### ISSUE TITLE
Not consistently scrolling to object after navigating back from digital view

### ISSUE THREAD

**Issue by HaSistrunk** [RockefellerArchiveCenter/dimes#448]
## Describe the bug
In minimap-squares branch, after viewing a digital object from the collection content, the browser back button does not consistently result in the page scrolling to the object. Sometimes it just scrolls to its parent collection (it appears to alternate every other time).

## To reproduce
1. Go to /objects/8f5gAUeigWPkNs8wYnsGG7
2. Click on "View Online"
3. Hit the browser back button
4. Notice that it opens the object page, but does not scroll down to that object in the collection content
5. Click "View Online" again either from the object details or by scrolling down to the object in the content
6. Hit the browser back button
7. Notice that now it does scroll as expected

## Expected behavior
Every time you hit the browser back button from the digital object view, it should scroll you down to that object in the collection content.

**Comment by helrond** [comment]
My suspicion is that this is because the user is clicking on the "view online" button from the collection contents component, which means that the URL for the current item is not selected. So this is actually the behavior I'd expect in this situation. 

We could change this behavior so that clicking on the "View Online" button **first** sets the URL to that object's URL and then loads the view page? It would mean changing that from a simple link to a button and adding additional behaviors in the Javascript handler...

**Comment by HaSistrunk** [comment]
What you describe is a thing, but I don't think we necessarily need to adjust that behavior. In this case, though, even if I start by going directly to an object URL and clicking its "View Online" button, the browser back button from the viewer doesn't take me back to that object. The URL is the URL for that object, but it just doesn't scroll down to the object.

I'm only seeing this on the minimap-squares branch, not in base.

**Comment by helrond** [comment]
OK I have attempted to increase the timeout on the function which scrolls the current item into view. This is working for me locally but I would appreciate another test.

I'm also noting that this may potentially be related to the browser attempting to reset scroll location with [`history.scrollRestoration` API](https://developer.mozilla.org/en-US/docs/Web/API/History/scrollRestoration).

**Comment by HaSistrunk** [comment]
If I try it a few times I'm seeing it behave a bit differently each time I hit the back button - mostly scrolling to a place where the object is visible on the screen, but not always.

**Comment by helrond** [comment]
OK I'm _not_ able to reproduce the behavior you're describing. The item is always centered on the screen. This one is a bit of a head scratcher.

**Comment by HaSistrunk** [comment]
Huh, strange. Well it's basically getting me there even if it isn't always centered, so maybe we don't need to worry about this too much.
