### ISSUE TITLE
Minimap checkmarks are positioned differently in Safari

### ISSUE THREAD

**Issue by HaSistrunk** [RockefellerArchiveCenter/dimes#459]
## Describe the bug
In Safari, the checkmark indicating that a minimap box has been clicked appears in the top left instead of the top right of the box as it does in other browsers.

## To reproduce
Open DIMES in Safari and search/open a collection with minimap results. Click on a box.

## Expected behavior
As designed and as seen in Chrome and Firefox, the checkmark appears in the top right of the square.

## Error message or screenshots
![image](https://user-images.githubusercontent.com/15254041/150159548-d348bcb5-2d9e-409f-ae09-c0b18c26d472.png)

## Impact on your work
This is about design consistency, but has little to know impact on the function or use of the feature. Impact is very low. But since Safari is our second most commonly used browser to access DIMES, it makes sense that it be consistent.

**Comment by helrond** [comment]
I believe that the value `justify-content` property on `.minimap__record-hit` should be `flex-end`, not `right`
