### ISSUE TITLE
node 12.11.0 is incompatible with jest-matcher-utils@27.5.1

### ISSUE THREAD

**Issue by ctgraham** [RockefellerArchiveCenter/dimes#514]
## Describe the bug
[We are currently basing the build off of `node:12.11.0-alpine`](https://github.com/RockefellerArchiveCenter/dimes/blob/4241c1179fc953a3e1d77cf9952021e204f2f08f/Dockerfile#L1), but dependency `jest-matcher-utils@27.5.1` demands `"^10.13.0 || ^12.13.0 || ^14.15.0 || >=15.0.0". Got "12.11.0"`.

## To reproduce
1. `git clone https://github.com/RockefellerArchiveCenter/dimes; cd dimes`
2. `docker build .`
3. See error: "Found incompatible module."

## Expected behavior
A naive build should succeed.

## Error message or screenshots
```
Sending build context to Docker daemon  1.249MB
Step 1/13 : FROM node:12.11.0-alpine as build
 ---> d1be9f6b8ac1
Step 2/13 : WORKDIR /app
 ---> Running in 952ab2d9efc0
Removing intermediate container 952ab2d9efc0
 ---> 0b7b18409399
Step 3/13 : ENV PATH /app/node_modules/.bin:$PATH
 ---> Running in 254abaedc62d
Removing intermediate container 254abaedc62d
 ---> 3e191080310f
Step 4/13 : COPY package.json yarn.lock ./
 ---> f55deaabac56
Step 5/13 : RUN yarn install --silent
 ---> Running in 7cb275fa8aa9
error jest-matcher-utils@27.5.1: The engine "node" is incompatible with this module. Expected version "^10.13.0 || ^12.13.0 || ^14.15.0 || >=15.0.0". Got "12.11.0"
error Found incompatible module.
The command '/bin/sh -c yarn install --silent' returned a non-zero code: 1
```

## Impact on your work
```
FROM node:14.17.0-alpine as build
```
appears to succeed as a replacement base.

## Additional context
n/a

**Comment by helrond** [comment]
@ctgraham Thanks for this, and apologies for the long delay in responding. We are not actually using the Dockerfile at all, which is why this bug is cropping up. I'm going to update the CI pipeline so we're building from the Dockerfile. Do you have a preference on updating to a specific version tag of node (i.e. `node:14.17.0-alpine`) or a more semantic tag like `node:lts-alpine`)?

**Comment by ctgraham** [comment]
No preference here.
