### ISSUE TITLE
Agent related collections matches number not accurate

### ISSUE THREAD

**Issue by HaSistrunk** [RockefellerArchiveCenter/dimes#520]
## Describe the bug
The number of matches indicated in each related collection on the agent pages are inaccurate. They appear to be giving the number of matches for the search term query instead of for the agent name query.  PR #512 adjusted the logic of the related collections, and the matches need to also reflect that change . This is in the `issue-46` branch.

## To reproduce
1. Search for "music education", limit result to agents, and select the "Norman Lloyd" agent.
2. See the number of matches in the "Related Collections" section.
3. Note that the Rockefeller Foundations records indicate 5 matches. Select the RF collection.
4. See from the minimap that there are actually only 3 matches.

## Expected behavior
Number of matches should match the agent query, not the search term query.

**Comment by helrond** [comment]
@HaSistrunk I am seeing that a search for `norman lloyd` returns five hits in the RF collection. I think this is one of those cases where there are collection-level hits that are being ignored by the minimap. The queries that are being used all look correct.

**Comment by HaSistrunk** [comment]
Oh, I see why I was confused. The current deployed DIMES from `base` shows agent related collection matches numbers that correspond to the agent name regardless of the search query, but when you click into the collection it shows you minimap matches based on the search query. So when I was comparing the number of matches between the `issue-46` branch and the `base` branch with a non-agent-name search query, they were always the same which I was not expecting.

I'll go ahead and close this issue.
