### ISSUE TITLE
Invalid email address

### ISSUE THREAD

**Issue by ctgraham** [RockefellerArchiveCenter/dimes#543]
https://github.com/RockefellerArchiveCenter/dimes/blob/0c79739ea0401972827777b25103806da105e653/src/components/PageBackendError/index.js#L18

Given that you don't obscure email addresses elsewhere, and given the use of the `mailto:` protocol, you probably meant this to have the `@` sign.

**Comment by helrond** [comment]
🤦‍♂️

**Comment by helrond** [comment]
@ctgraham I see there are a couple of other places where this email is hardcoded:
- the site footer
- the "Schedule a Research Appointment" button on the My List page
- the Duplication Request modal

Is it worth thinking a bit more about whether these things should be configurable, or is that getting too far down a rabbit hole?

**Comment by ctgraham** [comment]
It's a rabbit hole that I am hoping to dedicate some staff time to.  In particular, I'm thinking we should leverage some i18n / l10n modules to enable both translation and customization of the text in the UI.  I should probably open a new issue for that so we can discuss and scope and strategize.

**Comment by helrond** [comment]
Sounds like a plan! I'll PR and fix this mistake.
