### ISSUE TITLE
Minimap does not change view type on page resize without reloading the page

### ISSUE THREAD

**Issue by Tyl13** [RockefellerArchiveCenter/dimes#589]
## Describe the bug
If you zoom in while on a page with the minimap shown in the center of the page, then the minimap stays. It however is displayed at the bottom of the page on the Collection Details side within the Footer, and stays contained within the main body on the Collection Content side. The opposite issues also happens for when the minimap is separated into its own button. Zooming out leaves the button on the screen in the top right corner, and the minimap is not displayed within the middle of the page between the two other sections.

## To reproduce
1. Go to this [collection](https://dimes.rockarch.org/collections/T86vXyBGLtW2s626VCHhLA?category=&limit=40&query=s), or any other on [https://dimes.rockarch.org/](https://dimes.rockarch.org/)
2. Zoom in the screen to where the page separates with the button to jump to the other section at the bottom.
3. See Error: The minimap should still exists either in the Footer or just on the screen, and the button does not appear.
4. Refreshing the page while zoomed in will remove the minimap and add the button.
5. Zoom out with the button on the page until the page is no longer separated.
6. See Error: The button should still exist, without the minimap between the sections.

## Expected behavior
I expect the resizing of the webpage would remove the minimap and add the button to access it when the page becomes smaller, and for the inverse to happen when the page becomes bigger.

## Error message or screenshots
![image](https://user-images.githubusercontent.com/48526589/230954850-82b83438-551d-4a81-b6f3-56a0bf070bbb.png)
![image](https://user-images.githubusercontent.com/48526589/230955261-5fab9b67-c695-4b85-9b74-9c60ff75c0c8.png)
![image](https://user-images.githubusercontent.com/48526589/230955981-b962d202-9e75-45ce-a582-752c39d71360.png)

## Impact on your work
This doesn't impact my work, but is an odd issue that might confuse users.

## Additional context

The first screenshot is within my current build that I'm working on for the Translation work. The other screenshots are from the public dimes version.](https://dimes.rockarch.org/) I expect that the fix done in #461 should work to also fix this. However, I did not explore how that fix was done.

**Comment by helrond** [comment]
I am thinking this might have less to do with the minimap and more to do with how the `PageRecords` component determines device width, which uses an `isDesktop` helper that should probably be wrapped in the ResizeObserver.

**Comment by helrond** [comment]
Confirmed this is because of the static setting of `isDesktop` in this component. I'm working on a fix but I want to do this across all the component which use either `isDesktop` or `isMobile`.

**Comment by helrond** [comment]
@Tyl13 I just pushed up a branch that should address this. Can you take a look at let me know if it's working for you?

**Comment by Tyl13** [comment]
@helrond So, it does work to a point. When you zoom in, the minimap is removed and the button appears. However, clicking the button causes its own error. 
![image](https://user-images.githubusercontent.com/48526589/231281471-1a932731-fe97-439b-a3c1-79e6154651fa.png)

This is the same when zooming back out. The minimap being re added to the middle of the screen causes the same error.
![image](https://user-images.githubusercontent.com/48526589/231281604-1138837e-5d94-4f26-856f-4fd2a675674d.png)


This seems to be happening because the new element is causing a resize loop. https://github.com/juggle/resize-observer/issues/103

**Comment by helrond** [comment]
Ah, thanks for that @Tyl13. I think I resolved that issue - can you give it another shot?

**Comment by Tyl13** [comment]
@helrond Yeah, its working for me with no issues now. Thanks.
