### ISSUE TITLE
Improve dropdown component functionality

### ISSUE THREAD

**Issue by HaSistrunk** [RockefellerArchiveCenter/dimes#60]
## Describe
Improve support for keyboard navigation (which we need to support on mobile for screen readers) for the dropdown component. Functionally, 

## Expected behavior
Ideally, it should probably be navigable using the arrow keys to select the menu items, and esc/clicking outside the menu should close it.

## Additional context
Needs a little research on the best way to implement. This may be a good starting place: https://davatron5000.github.io/a11y-nutrition-cards/components/menu

**Comment by helrond** [comment]
This looks promising: https://www.npmjs.com/package/react-accessible-dropdown-menu-hook
