### ISSUE TITLE
Text strings are replacing UI elements

### ISSUE THREAD

**Issue by HaSistrunk** [RockefellerArchiveCenter/dimes#619]
## Describe the bug
View Online and Download buttons are being replaced with text strings in the UI on the /object page in record details and on the /list page.

## To reproduce
1. Go to dimes.rockarch.org/objects/DQCoJGgCRXHnsPjKGiaCsZ
2. See buttons in records details
3. Add this item to your list
4. Go to /list page
5. See that "View Online" button is replaced with string of text

## Error message or screenshots
<img width="493" alt="image" src="https://github.com/RockefellerArchiveCenter/dimes/assets/15254041/bd5e836d-ff41-437b-b0dd-1d4bca5273be">

Should be: 
<img width="483" alt="image" src="https://github.com/RockefellerArchiveCenter/dimes/assets/15254041/b63b5056-b2df-4f0a-9a53-364ac20a359d">

And on My List page:
<img width="908" alt="image" src="https://github.com/RockefellerArchiveCenter/dimes/assets/15254041/ec8d7d03-a35f-4dde-a8bc-d0ddaf532e43">

Should be:
<img width="878" alt="image" src="https://github.com/RockefellerArchiveCenter/dimes/assets/15254041/62927377-51fe-4b38-a251-00a9b6eee77d">

## Additional context
This seems to be a bug related to the lingui translations, because those text strings are present in `/src/locales/en/messages.js`. However, I'm not seeing it in local development.

**Comment by HaSistrunk** [comment]
I'm also seeing this phenomenon in the footer:

<img width="726" alt="image" src="https://github.com/RockefellerArchiveCenter/dimes/assets/15254041/ec24dac5-9eea-4a05-a186-a05a796e148a">

**Comment by helrond** [comment]
Running `yarn extract` and `yarn compile` (which extracts and compiles messages using `lingui`) appears to have done the trick. 

I think there are a couple of things we should do as a followup:
- Update the readme with a bit more information about when and how to extract and compile messages
- Consider rolling this into git pre-commit hooks and/or our CI pipeline in general
