### ISSUE TITLE
Improve lingui implementation

### ISSUE THREAD

**Issue by helrond** [RockefellerArchiveCenter/dimes#627]
## Is your feature request related to a problem? Please describe.
Current documentation and implementation of `lingui` is barebones and could use improvement to make things easier for other developers/our future selves.

## Describe the solution you'd like
We should do at least two things:
- Update the readme with a bit more information about when and how to extract and compile messages
- Consider rolling the extract and compile processes into git pre-commit hooks and/or our CI pipeline in general

## Describe alternatives you've considered
Could also consider ignoring `lingui` output files and making extract and compile part of the build process.

**Comment by p-galligan** [comment]
Closing. Fixed by #649 and others to update lingui translations
