### ISSUE TITLE
Add styles for select box options

### ISSUE THREAD

**Issue by HaSistrunk** [RockefellerArchiveCenter/dimes#64]
## Is your feature request related to a problem? Please describe.
It is difficult to add custom styles to select dropdowns. We have a Select component with styling on the Select element, but those styles do not inherit to the options. 

## Describe the solution you'd like
Figure out how to style the box containing the options when you click on a select box and implement to match designs.

## Describe alternatives you've considered
Use an existing library or build a custom control that copies the functionality of the select dropdown.

## Additional context
[https://developer.mozilla.org/en-US/docs/Learn/Forms/Advanced_form_styling](https://developer.mozilla.org/en-US/docs/Learn/Forms/Advanced_form_styling)

**Comment by helrond** [comment]
@HaSistrunk what would you think of using a `ul` and styling it to look like we want? https://24ways.org/2019/making-a-better-custom-select-element/

**Comment by HaSistrunk** [comment]
I like it. That's a pretty cool solution.
