### ISSUE TITLE
Improve accessibility of date inputs

### ISSUE THREAD

**Issue by helrond** [RockefellerArchiveCenter/dimes#80]
## Is your feature request related to a problem? Please describe.
Date inputs behave differently across browsers, and in some cases appear to not be accessible.

## Describe the solution you'd like
Research this problem a little more and determine a good solution. See https://www.hassellinclusion.com/blog/input-type-date-ready-for-use/ for an overview.

**Comment by helrond** [comment]
The pattern we ended up using in the library project was a text input (with a `format` attribute) along with a datepicker triggered by a button. I think that's a reasonable approach here too. Thoughts?

**Comment by HaSistrunk** [comment]
Yeah, I think that worked well.
