### ISSUE TITLE
Connect My List selected items to modal items

### ISSUE THREAD

**Issue by HaSistrunk** [RockefellerArchiveCenter/dimes#87]
## Is your feature request related to a problem? Please describe.
When a user unchecks checkbox inputs on the My List page for items, and then chooses an action such as "Request in Reading Room", "Request Copies", or "Email List" for those items, only the checked items should show up in the modal. Otherwise, they have to unselect unwanted items multiple times.

Either there should be no option to uncheck items on the My List page (ie. no checkbox inputs), or the unchecked items should not appear in the modal items list.

Sorry if I'm missing specifics about the mechanisms by which this is functioning. Hopefully this is clear.

**Comment by helrond** [comment]
Yeah, this makes sense. I think the interaction pattern in the current My List page matches what you describe.
